### ISSUE TITLE
New Host shows 45 year uptime

### ISSUE THREAD

**Issue by Tech-Nic** [opinkerfi/adagios#516]
Hello

When I create new Host with adagios it starts with a uptime of 45 year. after a time it goes back to "real-time" . It´s only a cosmetic issue as I can see.
![adagios_45years](https://cloud.githubusercontent.com/assets/10496931/5701600/d10dc29a-9a4d-11e4-89d5-5d6c0ba29a8d.png)
Adagios Version 1.6.1

**Comment by palli** [comment]
Yeah... Its a pain.

This is the way the underlying monitoring engine (nagios) displays the data.

In case of nagios web interface seems they have hacks all around the interface to change this to 'pending', but we need something cleaner to keep the code base sane.

**Comment by giner** [comment]
Why not checking for '0' and reporting just "ok" or "ok for uknown time" ? Should be easy change in code and it seems pretty sane to me.

**Comment by Nozlaf** [comment]
checking for 0 would do  nothing, because Nagios reports 45 years of uptime or downtime (depending on initial state) for any new host  that has been added but not had a check performed yet.
its technically a bug in nagios

I don't see it as an issue, id rather not see workarounds and hacks put into the web interface to cover up the underlying issue

 I'm guessing that the 45 year state comes  by virtue of needing a way to identify that it has never had a status check performed and as a Nagios admin I know if i see that it hasn't had a check done.

**Comment by giner** [comment]
That is not about up-time at all. This is about status age. When a new service is created Nagios reports 0 for a while and in some time it starts to report time of the last status change in seconds from 1970 (as I remember).

**Comment by giner** [comment]
For example, here is an extract from /var/cache/nagios3/status.dat:

    servicestatus {
        ...
        last_time_ok=1433934476
        last_time_warning=1433925116
        last_time_unknown=0
        last_time_critical=1433788976
        ...
        }

If status of this service is ok you see time calculated from 1433934476, but if status changes to unknown you are going to see "45 years" until this value is updated.

**Comment by giner** [comment]
The same is true for hoststatus.

**Comment by Nozlaf** [comment]
while some of my erarlier statement wasn't accurate you are confirming that Nagios reports 0 seconds since epoch

your suggestion to have adagios interpret the result of Unknown for 0 seconds since epoch as OK for unknown time for me isn't acceptable because I don't want adagios altering the state reported by Nagios in particular when adding a new host if the status is not known it should show as UNKNOWN 

so if the workaround was to hide the time if the value was 0 but keep the status as UNKNOWN that would be perfectly acceptable for me.

the reason why  I say this is that I am adding hosts frequently (via an automated process) and I want to see unknown if it has not yet been checked I cant have it falsely report OK

**Comment by giner** [comment]
I guess my explanation was not clear, sorry for that.

When I said "OK for unknown time" I meant "Real status for unknown time". The thing is that Nagios starts to report services status (whatever it is: ok, unknown, critical, warning) before last_time_unknown is updated. Therefore until it is updated we can show depending on status:
OK for unknown time
or
WARNING for unknown time
or
CRITICAL for unknown time
or
UNKNOWN for unknown time
instead of
OK for 45 years
or
WARNING for 45 years
or
CRITICAL for 45 years
or
UNKNOWN for 45 years

**Comment by Nozlaf** [comment]
ok yes that would work for me
