### ISSUE TITLE
Backup/restore option

### ISSUE THREAD

**Issue by boardstretcher** [opinkerfi/adagios#546]
As with any serious 'production' tool, this needs to have a way to press a button and get a backup of the entire configuration. Similarly, it should be possible to restore that configuration to a new install.

**Comment by palli** [comment]
That would primarily be the configuration files from the underlying monitoring engine (nagios). Backing them up should be easy easy.

Restoring on a new system is tricky because the main nagios config file is highly coupled with the extensions that have been installed, so it will not start up unless the exact same extensions have been installed.

Same with the object configuration file, the exact same set of plugins needs to be installed on the new system.

**Comment by boardstretcher** [comment]
Sounds like a good pseudocode description of the issue. I suggest scripting it out and offering a button in admin to do this. As you said it 'should be easy.'

Restoring on a new system shouldn't be hard. All you need is a restoration checker script. You upload your backup, it tells you 'before i can restore this, you need to install/enable x, y, and z. Try again after that.'

**Comment by spicysomtam** [comment]
This might help; this is what we do. Back it up locally and then scp it somewhere off the server. Occasionally where people have screwed up, I have restored individual host .cfg files back:

    # cat /usr/local/sbin/backup-nagios-adagios.sh
    #!/bin/bash

    SSH="ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null $1"
    SCP="scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null"
    BCKDIR=/var/lib/adagios-backup
    AGE=15

    tar -C / -cf /backup/nagios-adagios-backup-$(date '+%d%b%Y').tar etc/nagios usr/share/okconfig usr/lib64/nagios usr/local/bin usr/local/sbin

    $SSH "[ -d $BCKDIR ] || mkdir -p $BCKDIR"
    $SCP /backup/nagios-adagios-backup-$(date '+%d%b%Y').tar $1:$BCKDIR/

    find /backup -name "nagios-adagios-backup-*.tar" -mtime +$AGE -exec rm -f {} \;
    $SSH "find $BCKDIR -name \"nagios-adagios-backup-*.tar\" -mtime +$AGE -exec rm -f {} \;"
