### ISSUE TITLE
okconfig adagios and default templates

### ISSUE THREAD

**Issue by spicysomtam** [opinkerfi/adagios#566]
Playing around with adagios today and on the whole it works. However something that is not very clear: how do you update the default templates? Within the web interface you can configure everything, apart from these? Unless I have missed something; maybe something subtle? Basically I want to tweak them to our needs; say a Linux host gets a set of default checks (in our case we use snmp extensively and not nrpe which would require lots of client setups).

Other thing that is lacking is some documentation. Specifically a getting started/overview of adagios? I know developers hate writing documentation! Appreciate this is open source, but corporate management like this sort of thing, even if the software is free.

**Comment by spicysomtam** [comment]
We kind of want to customise the default templates under /usr/share/okconfig/templates. Mostly we use snmp for monitoring and use nrpe selectively. You would be amazed how much can be monitored via snmp. Anyhow, what is the impact of making changes under here for future upgrades of okconfig? Also, is there any plan to allow default templates to be edited via the web interface? Basically we want to add a linux host and then assign the linux default template to it (customised to our needs). It appears for now I will have to edit the files under /usr/share/okconfig/templates manually (Or use okconfig /pynag)?

BTW like the okconfig/pynag functionality; plenty of scope for automating the adding of hosts automatically to nagios from a provisionig system, etc.

Also adagios seems pretty good. Highly configurable (apart from the default templates).

**Comment by spicysomtam** [comment]
Kind of worked it out myself and added to your wiki docs: https://github.com/opinkerfi/adagios/wiki/Customising-okconfig-templates-to-your-needs

**Comment by Nozlaf** [comment]
thanks for writing that up, its probably going to help me with my current project

**Comment by pall-valmundsson** [comment]
Hi. I just realized there's basically no documentation for this feature. You can do this without editing the templates/examples in /usr/share/okconfig. You really shouldn't edit those as any update to the okconfig package *will overwrite the changes*.

For those who read python: https://github.com/opinkerfi/okconfig/blob/master/okconfig/__init__.py#L384-L402
https://github.com/opinkerfi/okconfig/blob/master/okconfig/config.py#L31

Basically what this does is look for example files inside your configured destination directory + "/examples" AND it will prefer those examples if there's a name conflict. You can therefor create your own custom examples which will then be available as templates as well as override the default okconfig templates with your own examples. The easiest way would be to just copy an example from /usr/share/okconfig and change that.

I've created a bunch of local template packages for various things that are relevant for my setup.

I would suggest experimenting with that and then revising the wiki article, since editing the default templates in /usr/share/okconfig can blow up.

**Comment by spicysomtam** [comment]
What do you mean by "your configured destination directory"? Can you give an example based on a centos setup following your install docs. Thanks! PS: it would be nice to have a feature in adagios to manage these templates.

I will revise the wiki page once I have worked it out. Actually I am quite happy to add pages as I work things out as we are quite impressed with adagios, and it does need some documentation.

I will try and read the python code when I have a bigger screen than my smartphone!

**Comment by spicysomtam** [comment]
Think you mean /etc/nagios/okconfig/examples?

**Comment by pall-valmundsson** [comment]
Yes. By default it looks there. It follows `destination_directory` in `/etc/okconfig.conf`.

**Comment by spicysomtam** [comment]
Its working fine now as per your guidance; I copied the default template to a new template under /etc/nagios/okconfig/examples, modified that and restored back the original example templates under /usr/share/okconfig/examples. I also updated the wiki page.

**Comment by spicysomtam** [comment]
Thanks for the help.
