### ISSUE TITLE
ERROR: do not start naemon as root user.

### ISSUE THREAD

**Issue by raxisa** [opinkerfi/adagios#619]
Naemon Core 1.0.6-pkg
Adagios version: 1.6.3-1.git.0.8f4ef6b.el7.centos

Attempts to verify configuration via 'Nagios Service > Verify' result in the following warning / error:

ERROR: do not start naemon as root user.

This is a brand new installation (as of post date), using the following guide.

https://github.com/opinkerfi/adagios/wiki/Naemon-and-Adagios-Install-Guide

Running the verification/pre-flight check from CLI as root results in the same issue (by design) however switching user to 'naemon' works as expected.

Unfortunately I'm not sure where / how to fix this. Please advise. Thanks!

**Comment by gardart** [comment]
The guide has been updated, should work with Nagios 4 and Naemon

**Comment by raxisa** [comment]
Followed the latest guide (vanilla build) in a bid to test. Issue has not been resolved.

**Comment by Xiofett** [comment]
I also stumbled across this problem. It happened after I deleted the default devices that came with the install.

What I found was that /etc/naemon/conf.d/windows.cfg contained a reference to one of the deleted devices.

Since I didn't need any of the defaults, I removed the windows.cfg, printer.cfg, and switch.cfg files. Restarting the service from the command line then worked.

So that error is misleading. I would guess it's something to do with the differences between Nagios and Naemon.

**Comment by raxisa** [comment]
@Xiofett I'm afraid what you're describing isn't related as this isn't about restarting services, it's about running pre-flight checks / configuration verification. If you attempt to Verify config (since you corrected the dependency issues you describe) you'll find the message 'ERROR: do not start naemon as root user.' still appears. In summary, the only way to reload run a pre-flight check at present is via the CLI.

**Comment by bouncingsoles** [comment]
If there is some way to add the flag --allow-root to naemon when running via Adagios gui?  That would allow the check to run so you don't need to login via the CLI.  Is there a way to do this via sudoers?
