### ISSUE TITLE
[RFE]adagios setting not supporting centos 7

### ISSUE THREAD

**Issue by tjyang** [opinkerfi/adagios#638]
Hi 

Please support systemd to start/stop/reload/status

* Still expecting init script from chkconfig.

![image](https://user-images.githubusercontent.com/378638/35769333-1d2b4d94-08cf-11e8-81f5-875dacbc4e26.png)

**Comment by gardart** [comment]
You can use any script in this field to handle start/stop/reload of Nagios service. By default it uses the "Nagios service" field to start/stop/reload the Nagios service with systemd on EL7. For example if you use Naemon instead of Nagios as a monitoring backend, you should change "Nagios service" = naemon.

We will check and see if we find better names for the fields to make this a bit more clear.
